#!/bin/sh

# the following is chkconfig init header
#
# zstack-iscsi:  zstack filesystem based ISCSI agent daemon
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by zstack management server \
#               to perform backup storage related operations\
#               See http://zstack.org
#
# processname: iscsifilesystemagent
# pidfile: /var/run/zstack/iscsi-filesystem-agent.pid
#

check_status() {
    pidfile='/var/run/zstack/iscsi-filesystem-agent.pid'
	if [ ! -f $pidfile ]; then
		echo "zstack iscsi agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "zstack iscsi agent is running, pid is $pid"
			exit 0
		else
			echo "zstack iscsi is stopped, but pidfile at $pidfile is not cleaned. It may be caused by the agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/zstack/virtualenv/iscsi/bin/activate && python -c "from iscsifilesystemagent import idaemon; idaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ zstack iscsi agent .... SUCCESS"
    exit 0
else
    echo "$@ zstack iscsi agent .... FAILED"
    exit 1
fi
