#!/bin/sh

# the following is chkconfig init header
#
# zstack-ceph-backupstorage:  zstack ceph backup storage agent daemon
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by zstack management server \
#               to perform backup storage related operations\
#               See http://zstack.org
#
# processname: zstack-ceph-backupstorage
# pidfile: /var/run/zstack/ceph-backupstorage.pid
#

check_status() {
    pidfile='/var/run/zstack/ceph-backupstorage.pid'
	if [ ! -f $pidfile ]; then
		echo "zstack ceph-backupstorage agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "zstack ceph-backupstorage agent is running, pid is $pid"
			exit 0
		else
			echo "zstack ceph-backupstorage is stopped, but pidfile at $pidfile is not cleaned. It may be caused by the agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/zstack/virtualenv/cephb/bin/activate && python -c "from cephbackupstorage import cdaemon; cdaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ zstack ceph-backupstorage agent .... SUCCESS"
    exit 0
else
    echo "$@ zstack ceph-backupstorage agent .... FAILED"
    exit 1
fi
