#!/usr/bin/python

__author__ = 'frank'

import sys
import httplib
import logging
import traceback
import time

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(levelname)s %(message)s',
                    filename='/var/log/zstack/libvirt-hook-qemu.log',
                    filemode='w')

ops = ['started', 'stopped']
op = sys.argv[2]

if op not in ops:
    sys.exit(0)

URL = "http://127.0.0.1:7070"
PATH = "/vm/reportstate"

params = ' '.join(sys.argv[1:])

def post():
    for i in range(0, 5):
        try:
            conn = httplib.HTTPSConnection(URL)
            conn.request('POST', PATH, params)
            res = conn.getresponse()
            if res.status != 200:
                raise Exception(res.read())
            conn.close()
        except Exception as e:
            content = traceback.format_exc()
            logging.warn('unable to post to %s%s with params[%s], %s.\n %s' % (URL, PATH, params, str(e), content))
            time.sleep(1)

try:
    post()
except:
    content = traceback.format_exc()
    logging.warn(content)

sys.exit(0)



