#!/bin/sh

# the following is chkconfig init header
#
# chkconfig: 345 97 03
# zstack-app-buildsystem:  zstack app buildsystem agent daemon
#
# processname: zstack-app-buildsystem
# pidfile: /var/run/zstack/app-buildsystem.pid
#

check_status() {
    pidfile='/var/run/zstack/app-buildsystem.pid'
	if [ ! -f $pidfile ]; then
		echo "zstack app-buildsystem agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "zstack app-buildsystem agent is running, pid is $pid"
			exit 0
		else
			echo "zstack app-buildsystem is stopped, but pidfile at $pidfile is not cleaned. It may be caused by the agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/zstack/virtualenv/appbuildsystem/bin/activate && python -c "from appbuildsystem import appdaemon; appdaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ zstack app-buildsystem agent .... SUCCESS"
    exit 0
else
    echo "$@ zstack app-buildsystem agent .... FAILED"
    exit 1
fi
