# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: SDS_4.2.300.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class EmailSendReqEmail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'body': 'str',
        'content_type': 'str',
        'to': 'list[str]'
    }

    attribute_map = {
        'body': 'body',
        'content_type': 'content_type',
        'to': 'to'
    }

    def __init__(self, body=None, content_type=None, to=None):  # noqa: E501
        """EmailSendReqEmail - a model defined in Swagger"""  # noqa: E501

        self._body = None
        self._content_type = None
        self._to = None
        self.discriminator = None

        self.body = body
        if content_type is not None:
            self.content_type = content_type
        self.to = to

    @property
    def body(self):
        """Gets the body of this EmailSendReqEmail.  # noqa: E501


        :return: The body of this EmailSendReqEmail.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this EmailSendReqEmail.


        :param body: The body of this EmailSendReqEmail.  # noqa: E501
        :type: str
        """
        if body is None:
            raise ValueError("Invalid value for `body`, must not be `None`")  # noqa: E501

        self._body = body

    @property
    def content_type(self):
        """Gets the content_type of this EmailSendReqEmail.  # noqa: E501

        content type, 'text/plain' or 'text/html'  # noqa: E501

        :return: The content_type of this EmailSendReqEmail.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this EmailSendReqEmail.

        content type, 'text/plain' or 'text/html'  # noqa: E501

        :param content_type: The content_type of this EmailSendReqEmail.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    @property
    def to(self):
        """Gets the to of this EmailSendReqEmail.  # noqa: E501


        :return: The to of this EmailSendReqEmail.  # noqa: E501
        :rtype: list[str]
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this EmailSendReqEmail.


        :param to: The to of this EmailSendReqEmail.  # noqa: E501
        :type: list[str]
        """
        if to is None:
            raise ValueError("Invalid value for `to`, must not be `None`")  # noqa: E501

        self._to = to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailSendReqEmail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
