# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: SDS_4.2.300.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from zstacklib.utils.xms_client.models.fs_client_group_nestview import FSClientGroupNestview  # noqa: F401,E501
# from zstacklib.utils.xms_client.models.fs_client_nestview import FSClientNestview  # noqa: F401,E501
# from zstacklib.utils.xms_client.models.fsnfs_share_nestview import FSNFSShareNestview  # noqa: F401,E501


class FSNFSShareACL(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'all_squash': 'bool',
        'create': 'datetime',
        'fs_client': 'FSClientNestview',
        'fs_client_group': 'FSClientGroupNestview',
        'fs_nfs_share': 'FSNFSShareNestview',
        'id': 'int',
        'permission': 'str',
        'root_squash': 'bool',
        'sync': 'bool',
        'type': 'str',
        'update': 'datetime'
    }

    attribute_map = {
        'all_squash': 'all_squash',
        'create': 'create',
        'fs_client': 'fs_client',
        'fs_client_group': 'fs_client_group',
        'fs_nfs_share': 'fs_nfs_share',
        'id': 'id',
        'permission': 'permission',
        'root_squash': 'root_squash',
        'sync': 'sync',
        'type': 'type',
        'update': 'update'
    }

    def __init__(self, all_squash=None, create=None, fs_client=None, fs_client_group=None, fs_nfs_share=None, id=None, permission=None, root_squash=None, sync=None, type=None, update=None):  # noqa: E501
        """FSNFSShareACL - a model defined in Swagger"""  # noqa: E501

        self._all_squash = None
        self._create = None
        self._fs_client = None
        self._fs_client_group = None
        self._fs_nfs_share = None
        self._id = None
        self._permission = None
        self._root_squash = None
        self._sync = None
        self._type = None
        self._update = None
        self.discriminator = None

        if all_squash is not None:
            self.all_squash = all_squash
        if create is not None:
            self.create = create
        if fs_client is not None:
            self.fs_client = fs_client
        if fs_client_group is not None:
            self.fs_client_group = fs_client_group
        if fs_nfs_share is not None:
            self.fs_nfs_share = fs_nfs_share
        if id is not None:
            self.id = id
        if permission is not None:
            self.permission = permission
        if root_squash is not None:
            self.root_squash = root_squash
        if sync is not None:
            self.sync = sync
        if type is not None:
            self.type = type
        if update is not None:
            self.update = update

    @property
    def all_squash(self):
        """Gets the all_squash of this FSNFSShareACL.  # noqa: E501


        :return: The all_squash of this FSNFSShareACL.  # noqa: E501
        :rtype: bool
        """
        return self._all_squash

    @all_squash.setter
    def all_squash(self, all_squash):
        """Sets the all_squash of this FSNFSShareACL.


        :param all_squash: The all_squash of this FSNFSShareACL.  # noqa: E501
        :type: bool
        """

        self._all_squash = all_squash

    @property
    def create(self):
        """Gets the create of this FSNFSShareACL.  # noqa: E501


        :return: The create of this FSNFSShareACL.  # noqa: E501
        :rtype: datetime
        """
        return self._create

    @create.setter
    def create(self, create):
        """Sets the create of this FSNFSShareACL.


        :param create: The create of this FSNFSShareACL.  # noqa: E501
        :type: datetime
        """

        self._create = create

    @property
    def fs_client(self):
        """Gets the fs_client of this FSNFSShareACL.  # noqa: E501


        :return: The fs_client of this FSNFSShareACL.  # noqa: E501
        :rtype: FSClientNestview
        """
        return self._fs_client

    @fs_client.setter
    def fs_client(self, fs_client):
        """Sets the fs_client of this FSNFSShareACL.


        :param fs_client: The fs_client of this FSNFSShareACL.  # noqa: E501
        :type: FSClientNestview
        """

        self._fs_client = fs_client

    @property
    def fs_client_group(self):
        """Gets the fs_client_group of this FSNFSShareACL.  # noqa: E501


        :return: The fs_client_group of this FSNFSShareACL.  # noqa: E501
        :rtype: FSClientGroupNestview
        """
        return self._fs_client_group

    @fs_client_group.setter
    def fs_client_group(self, fs_client_group):
        """Sets the fs_client_group of this FSNFSShareACL.


        :param fs_client_group: The fs_client_group of this FSNFSShareACL.  # noqa: E501
        :type: FSClientGroupNestview
        """

        self._fs_client_group = fs_client_group

    @property
    def fs_nfs_share(self):
        """Gets the fs_nfs_share of this FSNFSShareACL.  # noqa: E501


        :return: The fs_nfs_share of this FSNFSShareACL.  # noqa: E501
        :rtype: FSNFSShareNestview
        """
        return self._fs_nfs_share

    @fs_nfs_share.setter
    def fs_nfs_share(self, fs_nfs_share):
        """Sets the fs_nfs_share of this FSNFSShareACL.


        :param fs_nfs_share: The fs_nfs_share of this FSNFSShareACL.  # noqa: E501
        :type: FSNFSShareNestview
        """

        self._fs_nfs_share = fs_nfs_share

    @property
    def id(self):
        """Gets the id of this FSNFSShareACL.  # noqa: E501


        :return: The id of this FSNFSShareACL.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FSNFSShareACL.


        :param id: The id of this FSNFSShareACL.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def permission(self):
        """Gets the permission of this FSNFSShareACL.  # noqa: E501


        :return: The permission of this FSNFSShareACL.  # noqa: E501
        :rtype: str
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this FSNFSShareACL.


        :param permission: The permission of this FSNFSShareACL.  # noqa: E501
        :type: str
        """

        self._permission = permission

    @property
    def root_squash(self):
        """Gets the root_squash of this FSNFSShareACL.  # noqa: E501


        :return: The root_squash of this FSNFSShareACL.  # noqa: E501
        :rtype: bool
        """
        return self._root_squash

    @root_squash.setter
    def root_squash(self, root_squash):
        """Sets the root_squash of this FSNFSShareACL.


        :param root_squash: The root_squash of this FSNFSShareACL.  # noqa: E501
        :type: bool
        """

        self._root_squash = root_squash

    @property
    def sync(self):
        """Gets the sync of this FSNFSShareACL.  # noqa: E501


        :return: The sync of this FSNFSShareACL.  # noqa: E501
        :rtype: bool
        """
        return self._sync

    @sync.setter
    def sync(self, sync):
        """Sets the sync of this FSNFSShareACL.


        :param sync: The sync of this FSNFSShareACL.  # noqa: E501
        :type: bool
        """

        self._sync = sync

    @property
    def type(self):
        """Gets the type of this FSNFSShareACL.  # noqa: E501


        :return: The type of this FSNFSShareACL.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FSNFSShareACL.


        :param type: The type of this FSNFSShareACL.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def update(self):
        """Gets the update of this FSNFSShareACL.  # noqa: E501


        :return: The update of this FSNFSShareACL.  # noqa: E501
        :rtype: datetime
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this FSNFSShareACL.


        :param update: The update of this FSNFSShareACL.  # noqa: E501
        :type: datetime
        """

        self._update = update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FSNFSShareACL):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
