# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: SDS_4.2.300.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class FSSMBShareUpdateReqShare(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acl_inherited': 'bool',
        'case_sensitive': 'bool',
        'recycled': 'bool'
    }

    attribute_map = {
        'acl_inherited': 'acl_inherited',
        'case_sensitive': 'case_sensitive',
        'recycled': 'recycled'
    }

    def __init__(self, acl_inherited=None, case_sensitive=None, recycled=None):  # noqa: E501
        """FSSMBShareUpdateReqShare - a model defined in Swagger"""  # noqa: E501

        self._acl_inherited = None
        self._case_sensitive = None
        self._recycled = None
        self.discriminator = None

        if acl_inherited is not None:
            self.acl_inherited = acl_inherited
        if case_sensitive is not None:
            self.case_sensitive = case_sensitive
        if recycled is not None:
            self.recycled = recycled

    @property
    def acl_inherited(self):
        """Gets the acl_inherited of this FSSMBShareUpdateReqShare.  # noqa: E501

        default acl status  # noqa: E501

        :return: The acl_inherited of this FSSMBShareUpdateReqShare.  # noqa: E501
        :rtype: bool
        """
        return self._acl_inherited

    @acl_inherited.setter
    def acl_inherited(self, acl_inherited):
        """Sets the acl_inherited of this FSSMBShareUpdateReqShare.

        default acl status  # noqa: E501

        :param acl_inherited: The acl_inherited of this FSSMBShareUpdateReqShare.  # noqa: E501
        :type: bool
        """

        self._acl_inherited = acl_inherited

    @property
    def case_sensitive(self):
        """Gets the case_sensitive of this FSSMBShareUpdateReqShare.  # noqa: E501

        case sensitive  # noqa: E501

        :return: The case_sensitive of this FSSMBShareUpdateReqShare.  # noqa: E501
        :rtype: bool
        """
        return self._case_sensitive

    @case_sensitive.setter
    def case_sensitive(self, case_sensitive):
        """Sets the case_sensitive of this FSSMBShareUpdateReqShare.

        case sensitive  # noqa: E501

        :param case_sensitive: The case_sensitive of this FSSMBShareUpdateReqShare.  # noqa: E501
        :type: bool
        """

        self._case_sensitive = case_sensitive

    @property
    def recycled(self):
        """Gets the recycled of this FSSMBShareUpdateReqShare.  # noqa: E501

        recycle status  # noqa: E501

        :return: The recycled of this FSSMBShareUpdateReqShare.  # noqa: E501
        :rtype: bool
        """
        return self._recycled

    @recycled.setter
    def recycled(self, recycled):
        """Sets the recycled of this FSSMBShareUpdateReqShare.

        recycle status  # noqa: E501

        :param recycled: The recycled of this FSSMBShareUpdateReqShare.  # noqa: E501
        :type: bool
        """

        self._recycled = recycled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FSSMBShareUpdateReqShare):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
