# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: SDS_4.2.300.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from zstacklib.utils.xms_client.models.network_diagnosis import NetworkDiagnosis  # noqa: F401,E501


class NetworkDiagnosesResp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'network_diagnoses': 'list[NetworkDiagnosis]'
    }

    attribute_map = {
        'network_diagnoses': 'network_diagnoses'
    }

    def __init__(self, network_diagnoses=None):  # noqa: E501
        """NetworkDiagnosesResp - a model defined in Swagger"""  # noqa: E501

        self._network_diagnoses = None
        self.discriminator = None

        self.network_diagnoses = network_diagnoses

    @property
    def network_diagnoses(self):
        """Gets the network_diagnoses of this NetworkDiagnosesResp.  # noqa: E501

        network diagnoses  # noqa: E501

        :return: The network_diagnoses of this NetworkDiagnosesResp.  # noqa: E501
        :rtype: list[NetworkDiagnosis]
        """
        return self._network_diagnoses

    @network_diagnoses.setter
    def network_diagnoses(self, network_diagnoses):
        """Sets the network_diagnoses of this NetworkDiagnosesResp.

        network diagnoses  # noqa: E501

        :param network_diagnoses: The network_diagnoses of this NetworkDiagnosesResp.  # noqa: E501
        :type: list[NetworkDiagnosis]
        """
        if network_diagnoses is None:
            raise ValueError("Invalid value for `network_diagnoses`, must not be `None`")  # noqa: E501

        self._network_diagnoses = network_diagnoses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkDiagnosesResp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
