# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: SDS_4.2.300.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six

# from zstacklib.utils.xms_client.models.host_nestview import HostNestview  # noqa: F401,E501
# from zstacklib.utils.xms_client.models.object_storage_zone_nestview import ObjectStorageZoneNestview  # noqa: F401,E501


class ObjectStorageGateway(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create': 'datetime',
        'description': 'str',
        'etag': 'str',
        'gateway_ip': 'str',
        'gateway_name': 'str',
        'host': 'HostNestview',
        'id': 'int',
        'name': 'str',
        'os_zone': 'ObjectStorageZoneNestview',
        'port': 'int',
        'role': 'str',
        'status': 'str',
        'update': 'datetime'
    }

    attribute_map = {
        'create': 'create',
        'description': 'description',
        'etag': 'etag',
        'gateway_ip': 'gateway_ip',
        'gateway_name': 'gateway_name',
        'host': 'host',
        'id': 'id',
        'name': 'name',
        'os_zone': 'os_zone',
        'port': 'port',
        'role': 'role',
        'status': 'status',
        'update': 'update'
    }

    def __init__(self, create=None, description=None, etag=None, gateway_ip=None, gateway_name=None, host=None, id=None, name=None, os_zone=None, port=None, role=None, status=None, update=None):  # noqa: E501
        """ObjectStorageGateway - a model defined in Swagger"""  # noqa: E501

        self._create = None
        self._description = None
        self._etag = None
        self._gateway_ip = None
        self._gateway_name = None
        self._host = None
        self._id = None
        self._name = None
        self._os_zone = None
        self._port = None
        self._role = None
        self._status = None
        self._update = None
        self.discriminator = None

        if create is not None:
            self.create = create
        if description is not None:
            self.description = description
        if etag is not None:
            self.etag = etag
        if gateway_ip is not None:
            self.gateway_ip = gateway_ip
        if gateway_name is not None:
            self.gateway_name = gateway_name
        if host is not None:
            self.host = host
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if os_zone is not None:
            self.os_zone = os_zone
        if port is not None:
            self.port = port
        if role is not None:
            self.role = role
        if status is not None:
            self.status = status
        if update is not None:
            self.update = update

    @property
    def create(self):
        """Gets the create of this ObjectStorageGateway.  # noqa: E501


        :return: The create of this ObjectStorageGateway.  # noqa: E501
        :rtype: datetime
        """
        return self._create

    @create.setter
    def create(self, create):
        """Sets the create of this ObjectStorageGateway.


        :param create: The create of this ObjectStorageGateway.  # noqa: E501
        :type: datetime
        """

        self._create = create

    @property
    def description(self):
        """Gets the description of this ObjectStorageGateway.  # noqa: E501


        :return: The description of this ObjectStorageGateway.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ObjectStorageGateway.


        :param description: The description of this ObjectStorageGateway.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def etag(self):
        """Gets the etag of this ObjectStorageGateway.  # noqa: E501


        :return: The etag of this ObjectStorageGateway.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this ObjectStorageGateway.


        :param etag: The etag of this ObjectStorageGateway.  # noqa: E501
        :type: str
        """

        self._etag = etag

    @property
    def gateway_ip(self):
        """Gets the gateway_ip of this ObjectStorageGateway.  # noqa: E501


        :return: The gateway_ip of this ObjectStorageGateway.  # noqa: E501
        :rtype: str
        """
        return self._gateway_ip

    @gateway_ip.setter
    def gateway_ip(self, gateway_ip):
        """Sets the gateway_ip of this ObjectStorageGateway.


        :param gateway_ip: The gateway_ip of this ObjectStorageGateway.  # noqa: E501
        :type: str
        """

        self._gateway_ip = gateway_ip

    @property
    def gateway_name(self):
        """Gets the gateway_name of this ObjectStorageGateway.  # noqa: E501


        :return: The gateway_name of this ObjectStorageGateway.  # noqa: E501
        :rtype: str
        """
        return self._gateway_name

    @gateway_name.setter
    def gateway_name(self, gateway_name):
        """Sets the gateway_name of this ObjectStorageGateway.


        :param gateway_name: The gateway_name of this ObjectStorageGateway.  # noqa: E501
        :type: str
        """

        self._gateway_name = gateway_name

    @property
    def host(self):
        """Gets the host of this ObjectStorageGateway.  # noqa: E501


        :return: The host of this ObjectStorageGateway.  # noqa: E501
        :rtype: HostNestview
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this ObjectStorageGateway.


        :param host: The host of this ObjectStorageGateway.  # noqa: E501
        :type: HostNestview
        """

        self._host = host

    @property
    def id(self):
        """Gets the id of this ObjectStorageGateway.  # noqa: E501


        :return: The id of this ObjectStorageGateway.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ObjectStorageGateway.


        :param id: The id of this ObjectStorageGateway.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ObjectStorageGateway.  # noqa: E501


        :return: The name of this ObjectStorageGateway.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ObjectStorageGateway.


        :param name: The name of this ObjectStorageGateway.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def os_zone(self):
        """Gets the os_zone of this ObjectStorageGateway.  # noqa: E501


        :return: The os_zone of this ObjectStorageGateway.  # noqa: E501
        :rtype: ObjectStorageZoneNestview
        """
        return self._os_zone

    @os_zone.setter
    def os_zone(self, os_zone):
        """Sets the os_zone of this ObjectStorageGateway.


        :param os_zone: The os_zone of this ObjectStorageGateway.  # noqa: E501
        :type: ObjectStorageZoneNestview
        """

        self._os_zone = os_zone

    @property
    def port(self):
        """Gets the port of this ObjectStorageGateway.  # noqa: E501


        :return: The port of this ObjectStorageGateway.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ObjectStorageGateway.


        :param port: The port of this ObjectStorageGateway.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def role(self):
        """Gets the role of this ObjectStorageGateway.  # noqa: E501


        :return: The role of this ObjectStorageGateway.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ObjectStorageGateway.


        :param role: The role of this ObjectStorageGateway.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def status(self):
        """Gets the status of this ObjectStorageGateway.  # noqa: E501


        :return: The status of this ObjectStorageGateway.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ObjectStorageGateway.


        :param status: The status of this ObjectStorageGateway.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def update(self):
        """Gets the update of this ObjectStorageGateway.  # noqa: E501


        :return: The update of this ObjectStorageGateway.  # noqa: E501
        :rtype: datetime
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this ObjectStorageGateway.


        :param update: The update of this ObjectStorageGateway.  # noqa: E501
        :type: datetime
        """

        self._update = update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectStorageGateway):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
