# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: SDS_4.2.300.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class ObjectStorageBucketNFSClientsCreateReqClientsElt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client': 'str',
        'permission': 'str'
    }

    attribute_map = {
        'client': 'client',
        'permission': 'permission'
    }

    def __init__(self, client=None, permission=None):  # noqa: E501
        """ObjectStorageBucketNFSClientsCreateReqClientsElt - a model defined in Swagger"""  # noqa: E501

        self._client = None
        self._permission = None
        self.discriminator = None

        self.client = client
        self.permission = permission

    @property
    def client(self):
        """Gets the client of this ObjectStorageBucketNFSClientsCreateReqClientsElt.  # noqa: E501


        :return: The client of this ObjectStorageBucketNFSClientsCreateReqClientsElt.  # noqa: E501
        :rtype: str
        """
        return self._client

    @client.setter
    def client(self, client):
        """Sets the client of this ObjectStorageBucketNFSClientsCreateReqClientsElt.


        :param client: The client of this ObjectStorageBucketNFSClientsCreateReqClientsElt.  # noqa: E501
        :type: str
        """
        if client is None:
            raise ValueError("Invalid value for `client`, must not be `None`")  # noqa: E501

        self._client = client

    @property
    def permission(self):
        """Gets the permission of this ObjectStorageBucketNFSClientsCreateReqClientsElt.  # noqa: E501


        :return: The permission of this ObjectStorageBucketNFSClientsCreateReqClientsElt.  # noqa: E501
        :rtype: str
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this ObjectStorageBucketNFSClientsCreateReqClientsElt.


        :param permission: The permission of this ObjectStorageBucketNFSClientsCreateReqClientsElt.  # noqa: E501
        :type: str
        """
        if permission is None:
            raise ValueError("Invalid value for `permission`, must not be `None`")  # noqa: E501

        self._permission = permission

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectStorageBucketNFSClientsCreateReqClientsElt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
