# coding: utf-8

"""
    XMS API

    XMS is the controller of distributed storage system  # noqa: E501

    OpenAPI spec version: SDS_4.2.300.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401
import six


class SSLCertificateNestview(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'force_https': 'bool',
        'id': 'int',
        'name': 'str'
    }

    attribute_map = {
        'force_https': 'force_https',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, force_https=None, id=None, name=None):  # noqa: E501
        """SSLCertificateNestview - a model defined in Swagger"""  # noqa: E501

        self._force_https = None
        self._id = None
        self._name = None
        self.discriminator = None

        if force_https is not None:
            self.force_https = force_https
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name

    @property
    def force_https(self):
        """Gets the force_https of this SSLCertificateNestview.  # noqa: E501

        redirect http request to https  # noqa: E501

        :return: The force_https of this SSLCertificateNestview.  # noqa: E501
        :rtype: bool
        """
        return self._force_https

    @force_https.setter
    def force_https(self, force_https):
        """Sets the force_https of this SSLCertificateNestview.

        redirect http request to https  # noqa: E501

        :param force_https: The force_https of this SSLCertificateNestview.  # noqa: E501
        :type: bool
        """

        self._force_https = force_https

    @property
    def id(self):
        """Gets the id of this SSLCertificateNestview.  # noqa: E501

        certificate id  # noqa: E501

        :return: The id of this SSLCertificateNestview.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SSLCertificateNestview.

        certificate id  # noqa: E501

        :param id: The id of this SSLCertificateNestview.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SSLCertificateNestview.  # noqa: E501

        certificate name  # noqa: E501

        :return: The name of this SSLCertificateNestview.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SSLCertificateNestview.

        certificate name  # noqa: E501

        :param name: The name of this SSLCertificateNestview.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SSLCertificateNestview):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
