#!/bin/sh
VIRTUAL_ENV=/var/lib/zstack/virtualenv/zstackctl
if [ ! -d $VIRTUAL_ENV ]; then
    echo "Need to install zstackctl before using it"
    exit 1
fi
. $VIRTUAL_ENV/bin/activate
python -c "from zstackctl import ctl; ctl.main()" $@
