#!/bin/sh

# the following is chkconfig init header
#
# zstack-console-proxy:  zstack sftp-console-proxy agent daemon
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by zstack management server \
#               to perform console proxy related operations\
#               See http://zstack.org
#
# processname: cdaemon
# pidfile: /var/run/zstack/zstack-console-proxy.pid
#

check_status() {
	pidfile='/var/run/zstack/zstack-console-proxy.pid'
	if [ ! -f $pidfile ]; then
		echo "zstack-console-proxy agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "zstack-console-proxy agent is running, pid is $pid"
			exit 0
		else
			echo "zstack-console-proxy is stopped, but pidfile at $pidfile is not cleaned. It may be caused by the agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/zstack/virtualenv/consoleproxy/bin/activate && python -c "from consoleproxy import cdaemon; cdaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ zstack-console-proxy agent .... SUCCESS"
    exit 0
else
    echo "$@ zstack-console-proxy agent .... FAILED"
    exit 1
fi
